#!/usr/bin/env perl
use Mojolicious::Lite;
use lib "$ENV{'HOME'}/dev/Video-PlaybackMachine/lib";
use Video::PlaybackMachine::Schema;
use DateTime;

our $Database_Name = "$ENV{'HOME'}/dev/Video-PlaybackMachine/bin/test.db";

helper 'timefmt' => sub {
	my $self = shift;
	my ($raw_time) = @_;
	
	my $dt = DateTime->from_epoch( epoch => $raw_time );
	
	$dt->set_time_zone('America/Los_Angeles');
	return $dt->ymd . " " . $dt->hms;
};

get '/' => sub {
  my $self = shift;
  
  my $schedule_name = $self->param('schedulename') // 'Test Schedule';
  
  my $schema = Video::PlaybackMachine::Schema->connect("dbi:SQLite:dbname=$Database_Name", '', '');

  my $schedule = $schema->resultset('Schedule')->find({ name => $schedule_name });
  
  $self->render('index',
  	schedule => $schedule
  );
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<h2><%= $schedule->name() %></h2>

<table>
<tr><th>Start</th><th>Title</th><th>End</th></tr>
% foreach my $entry ( $schedule->schedule_entries_in_order() ) {
<tr>
<td><%= timefmt( $entry->start_time ) %></td>
<td><%= $entry->movie_info->title() %></td>
<td><%= timefmt( $entry->schedule_entry_end->stop_time ) %></td>
</tr>
% }
</table>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
