#!/usr/bin/env perl
use Mojolicious::Lite;
use lib "$ENV{'HOME'}/dev/Video-PlaybackMachine/lib";
use Video::PlaybackMachine::Schema;

our $Database_Name = "$ENV{'HOME'}/dev/Video-PlaybackMachine/bin/test.db";

get '/' => sub {
  my $self = shift;
  
  my $schedule_name = $self->param('schedulename') // 'Test Schedule';
  
  my $schema = Video::PlaybackMachine::Schema->connect("dbi:SQLite:dbname=$Database_Name", '', '');

  my $schedule = $schema->resultset('Schedule')->find({ name => $schedule_name });
  
  $self->render('index',
  	schedule => $schedule
  );
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
Schedule is <%= $schedule->name() %>

% foreach my $entry ( $schedule->schedule_entries() ) {
<p><%= $entry->start_time %>, <%= $entry->mrl() %></p>
% }

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
